server:
  port: 8082

spring:
  application:
    name: account-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/account_db
    username: postgres
    password: postgres

  sql:
    init:
      mode: never

# Configuracion para comunicarse con customer-service
customer-service:
  base-url: http://localhost:8081/api/v1

logging:
  level:
    root: INFO
    com.banking.customer: DEBUG
    org.springframework.r2dbc: DEBUG

# Swagger UI / OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always